name = "forever-one"
main = "dist/_worker.js"
compatibility_date = "2026-04-09"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist"

[vars]
SUPABASE_URL = "https://wikofwhkvaelzgdxcjjo.supabase.co"
SUPABASE_ANON_KEY = "sb_publishable_OPmTwoGBzXlsw-tqTRhyPg_RTbIw4md"
PUBLIC_SUPABASE_URL = "https://wikofwhkvaelzgdxcjjo.supabase.co"
PUBLIC_SUPABASE_ANON = "sb_publishable_OPmTwoGBzXlsw-tqTRhyPg_RTbIw4md"
